ALTER TABLE "Organization"
  ADD COLUMN IF NOT EXISTS "taxRegime" TEXT NOT NULL DEFAULT 'simples',
  ADD COLUMN IF NOT EXISTS "defaultTaxPercent" DOUBLE PRECISION NOT NULL DEFAULT 6,
  ADD COLUMN IF NOT EXISTS "defaultPackagingCost" DOUBLE PRECISION NOT NULL DEFAULT 1.5,
  ADD COLUMN IF NOT EXISTS "targetMinMargin" DOUBLE PRECISION NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS "targetHealthyMargin" DOUBLE PRECISION NOT NULL DEFAULT 25;
